Alcaritty:
  env:
    TERM: alacritty
window:
  opacity: 0.8
  padding:
    x: 10
    y: 10
    decorations: none
    dynamic_title: false
    scrolling:
      history: 10000
      multiplier: 3
      font:
        normal:
          family: JetBrains Mono
          size: 13.0

          cursor:
            style:
              shape: Block
              blinking: Always
              blink_interval: 750
              unfocused_hollow: true
