#! /bin/sh

nm-applet &
sxhkd -c ~/.config/bspwm/sxhkdrc &
picom --config ~/.config/picom/picom.conf &
$HOME/.config/polybar/launch.sh &
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5

bspc config border_width         2
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Chromium desktop='^1'
bspc rule -a Firefox desktop='^1'
bspc rule -a Alacritty desktop='^2'
bspc rule -a Thunar desktop='^3'
