# If running from tty1 start bspwm
[ "$(tty)" = "/dev/tty1" ] && exec startx

export EDITOR="nvim"
export TERMINAL="kitty"
export TERM="kitty"
export BROWSER="firefox"
export FILE="joshuto"

export ZDOTDIR="$HOME/dotfiles/zsh/"

# Added by `rbenv init` on Thu Dec 12 18:23:21 GMT 2024
eval "$(~/.rbenv/bin/rbenv init - --no-rehash zsh)"
